### ISSUE TITLE
How to run it with quarkus?

### ISSUE THREAD

**Issue by mistreckless** [t1/graphql-federation-demo#1]
1. Run quarkusDev in the film service
2. Change this lines in gateway/index.tsx `        { name: 'film', url: 'http://localhost:8083/graphql' },  //      { name: 'review', url: 'http://localhost:8080/review/graphql' },
  //      { name: 'artist', url: 'http://localhost:8082/graphql' },`
2. Run gateway

Result

`Error checking for changes to service definitions: Couldn't load service definitions for "film" at http://localhost:8083/graphql: Validation error of type FieldUndefined: Field '_service' in type 'Query' is undefined @ '_service'
`
This looks like the film service didn't support federation. So, is it possible to make it works with quarkus?

**Comment by t1** [comment]
The Quarkus part is still in an early exploratory/experimental stage. We currently think about pulling it all into the existing Quarkus extension. Stay tuned!
